ansible_user: vyos01
ansible_ssh_private_key_file: "{{ playbook_dir }}/../.ssh/vyos"

interfaces:
    - name: eth0
      ipv4:
        - address: 10.0.12.1/24
    - name: eth1
      ipv4: 
        - address: 10.0.13.2/24

    - name: lo
      ipv4:
        - address: 10.0.0.1/32

    

OSPF:
  parameters:
    router_id: 10.0.0.1
  passive_interface:
    - lo
  areas:
    - area_id: 0
      network:
        - address: 10.0.12.0/24
        - address: 10.0.13.0/24
