ansible_user: vyos01
ansible_ssh_private_key_file: "{{ playbook_dir }}/../.ssh/vyos"

interfaces:
    - name: eth0
      ipv4:
        - address: 10.0.12.1/24
    - name: eth1
      ipv4: 
        - address: 10.0.13.2/24

    - name: lo
      ipv4:
        - address: 10.0.0.1/32

    

ospf:
  process_id: 1
  networks:
    - prefix: 10.0.12.0
      mask: 24
      area: 0

    - prefix: 10.0.13.0
      mask: 24
      area: 0
