ansible_user: cisco02

interfaces:
  - name: GigabitEthernet0/1
    ipv4: 
    - address: 10.0.12.2/24

  - name: GigabitEthernet0/0
    ipv4: 
    - address: 10.0.24.1/24

  - name: Loopback0
    ipv4: 
    - address: 10.0.0.2/32

OSPF:
  processes:
    - process_id: "1"
      areas:
      - area_id: "0"
      network:
        - address: 10.0.12.2
          wildcard_bits: 0.0.0.0
          area: 0
        - address: 10.0.24.1
          wildcard_bits: 0.0.0.0
          area: 0
